import './globals.css'
import type { Metadata } from 'next'
import { Chakra_Petch } from 'next/font/google'

const chakraPetch = Chakra_Petch({subsets:['latin','latin-ext','thai','vietnamese'], weight:['300','400','700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={chakraPetch.className+ ' bg-zinc-950  min-h-screen'}>{children}</body>
    </html>
  )
}
